name: iot_manager_grpc_api
description: OpenioTHub Dart gRPC.

version: 0.0.2+24

homepage: https://github.com/OpenIotHUb

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  async: ^2.2.0
  googleapis_auth: ^0.2.7
  meta: ^1.1.6
  http: ^0.12.0
  http2: ^1.0.0
  #  grpc
  grpc: ^1.0.2
  #  grpc协议
  protobuf: ^1.0.1
  fixnum: ^0.10.9

dev_dependencies:
  build_runner: ^1.5.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.1
  mockito: ^4.1.0
  test: ^1.6.4
