// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.1
// source: httpManager.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//手动添加的局域网主机
type HttpInfoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HttpInfoList []*HttpInfo `protobuf:"bytes,1,rep,name=HttpInfoList,proto3" json:"HttpInfoList,omitempty"`
}

func (x *HttpInfoList) Reset() {
	*x = HttpInfoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httpManager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpInfoList) ProtoMessage() {}

func (x *HttpInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_httpManager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpInfoList.ProtoReflect.Descriptor instead.
func (*HttpInfoList) Descriptor() ([]byte, []int) {
	return file_httpManager_proto_rawDescGZIP(), []int{0}
}

func (x *HttpInfoList) GetHttpInfoList() []*HttpInfo {
	if x != nil {
		return x.HttpInfoList
	}
	return nil
}

type HttpInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID        string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Port        int32  `protobuf:"varint,4,opt,name=Port,proto3" json:"Port,omitempty"`
	Domain      string `protobuf:"bytes,5,opt,name=Domain,proto3" json:"Domain,omitempty"`
	HostUUID    int64  `protobuf:"varint,6,opt,name=HostUUID,proto3" json:"HostUUID,omitempty"`
}

func (x *HttpInfo) Reset() {
	*x = HttpInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_httpManager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpInfo) ProtoMessage() {}

func (x *HttpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_httpManager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpInfo.ProtoReflect.Descriptor instead.
func (*HttpInfo) Descriptor() ([]byte, []int) {
	return file_httpManager_proto_rawDescGZIP(), []int{1}
}

func (x *HttpInfo) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *HttpInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HttpInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HttpInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HttpInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *HttpInfo) GetHostUUID() int64 {
	if x != nil {
		return x.HostUUID
	}
	return 0
}

var File_httpManager_proto protoreflect.FileDescriptor

var file_httpManager_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x74, 0x74, 0x70, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0c, 0x48, 0x74, 0x74, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0c, 0x48, 0x74, 0x74, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x48, 0x74, 0x74, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x48, 0x74, 0x74, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x08, 0x48, 0x74, 0x74, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x6f,
	0x73, 0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x48, 0x6f,
	0x73, 0x74, 0x55, 0x55, 0x49, 0x44, 0x32, 0xa7, 0x01, 0x0a, 0x0b, 0x48, 0x74, 0x74, 0x70, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x48, 0x74, 0x74, 0x70, 0x73, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x48, 0x74, 0x74, 0x70, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x74, 0x74,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30,
	0x0a, 0x07, 0x44, 0x65, 0x6c, 0x48, 0x74, 0x74, 0x70, 0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x74, 0x74, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_httpManager_proto_rawDescOnce sync.Once
	file_httpManager_proto_rawDescData = file_httpManager_proto_rawDesc
)

func file_httpManager_proto_rawDescGZIP() []byte {
	file_httpManager_proto_rawDescOnce.Do(func() {
		file_httpManager_proto_rawDescData = protoimpl.X.CompressGZIP(file_httpManager_proto_rawDescData)
	})
	return file_httpManager_proto_rawDescData
}

var file_httpManager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_httpManager_proto_goTypes = []interface{}{
	(*HttpInfoList)(nil),      // 0: pb.HttpInfoList
	(*HttpInfo)(nil),          // 1: pb.HttpInfo
	(*Empty)(nil),             // 2: pb.Empty
	(*OperationResponse)(nil), // 3: pb.OperationResponse
}
var file_httpManager_proto_depIdxs = []int32{
	1, // 0: pb.HttpInfoList.HttpInfoList:type_name -> pb.HttpInfo
	2, // 1: pb.HttpManager.GetAllHttps:input_type -> pb.Empty
	1, // 2: pb.HttpManager.AddOrUpdateHttp:input_type -> pb.HttpInfo
	1, // 3: pb.HttpManager.DelHttp:input_type -> pb.HttpInfo
	0, // 4: pb.HttpManager.GetAllHttps:output_type -> pb.HttpInfoList
	3, // 5: pb.HttpManager.AddOrUpdateHttp:output_type -> pb.OperationResponse
	3, // 6: pb.HttpManager.DelHttp:output_type -> pb.OperationResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_httpManager_proto_init() }
func file_httpManager_proto_init() {
	if File_httpManager_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_httpManager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpInfoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_httpManager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_httpManager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_httpManager_proto_goTypes,
		DependencyIndexes: file_httpManager_proto_depIdxs,
		MessageInfos:      file_httpManager_proto_msgTypes,
	}.Build()
	File_httpManager_proto = out.File
	file_httpManager_proto_rawDesc = nil
	file_httpManager_proto_goTypes = nil
	file_httpManager_proto_depIdxs = nil
}
