// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: mqttDeviceManager.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MqttDeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//    String ip;
	DeviceId string `protobuf:"bytes,1,opt,name=DeviceId,proto3" json:"DeviceId,omitempty"`
	//    int port;
	DeviceModel string `protobuf:"bytes,2,opt,name=DeviceModel,proto3" json:"DeviceModel,omitempty"`
}

func (x *MqttDeviceInfo) Reset() {
	*x = MqttDeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqttDeviceManager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MqttDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqttDeviceInfo) ProtoMessage() {}

func (x *MqttDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mqttDeviceManager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqttDeviceInfo.ProtoReflect.Descriptor instead.
func (*MqttDeviceInfo) Descriptor() ([]byte, []int) {
	return file_mqttDeviceManager_proto_rawDescGZIP(), []int{0}
}

func (x *MqttDeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *MqttDeviceInfo) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

type MqttDeviceInfoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MqttDeviceInfoList []*MqttDeviceInfo `protobuf:"bytes,1,rep,name=MqttDeviceInfoList,proto3" json:"MqttDeviceInfoList,omitempty"`
}

func (x *MqttDeviceInfoList) Reset() {
	*x = MqttDeviceInfoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqttDeviceManager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MqttDeviceInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqttDeviceInfoList) ProtoMessage() {}

func (x *MqttDeviceInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_mqttDeviceManager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqttDeviceInfoList.ProtoReflect.Descriptor instead.
func (*MqttDeviceInfoList) Descriptor() ([]byte, []int) {
	return file_mqttDeviceManager_proto_rawDescGZIP(), []int{1}
}

func (x *MqttDeviceInfoList) GetMqttDeviceInfoList() []*MqttDeviceInfo {
	if x != nil {
		return x.MqttDeviceInfoList
	}
	return nil
}

var File_mqttDeviceManager_proto protoreflect.FileDescriptor

var file_mqttDeviceManager_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0e, 0x4d,
	0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x58, 0x0a, 0x12, 0x4d,
	0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x42, 0x0a, 0x12, 0x4d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x12, 0x4d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xc8, 0x01, 0x0a, 0x11, 0x4d, 0x71, 0x74, 0x74, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0d, 0x41,
	0x64, 0x64, 0x4d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x4d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x4d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4d, 0x71, 0x74, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x09, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x71, 0x74, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqttDeviceManager_proto_rawDescOnce sync.Once
	file_mqttDeviceManager_proto_rawDescData = file_mqttDeviceManager_proto_rawDesc
)

func file_mqttDeviceManager_proto_rawDescGZIP() []byte {
	file_mqttDeviceManager_proto_rawDescOnce.Do(func() {
		file_mqttDeviceManager_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqttDeviceManager_proto_rawDescData)
	})
	return file_mqttDeviceManager_proto_rawDescData
}

var file_mqttDeviceManager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mqttDeviceManager_proto_goTypes = []interface{}{
	(*MqttDeviceInfo)(nil),     // 0: pb.MqttDeviceInfo
	(*MqttDeviceInfoList)(nil), // 1: pb.MqttDeviceInfoList
	(*Empty)(nil),              // 2: pb.Empty
	(*OperationResponse)(nil),  // 3: pb.OperationResponse
}
var file_mqttDeviceManager_proto_depIdxs = []int32{
	0, // 0: pb.MqttDeviceInfoList.MqttDeviceInfoList:type_name -> pb.MqttDeviceInfo
	0, // 1: pb.MqttDeviceManager.AddMqttDevice:input_type -> pb.MqttDeviceInfo
	0, // 2: pb.MqttDeviceManager.DelMqttDevice:input_type -> pb.MqttDeviceInfo
	2, // 3: pb.MqttDeviceManager.GetAllMqttDevice:input_type -> pb.Empty
	3, // 4: pb.MqttDeviceManager.AddMqttDevice:output_type -> pb.OperationResponse
	3, // 5: pb.MqttDeviceManager.DelMqttDevice:output_type -> pb.OperationResponse
	1, // 6: pb.MqttDeviceManager.GetAllMqttDevice:output_type -> pb.MqttDeviceInfoList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mqttDeviceManager_proto_init() }
func file_mqttDeviceManager_proto_init() {
	if File_mqttDeviceManager_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mqttDeviceManager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MqttDeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqttDeviceManager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MqttDeviceInfoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqttDeviceManager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mqttDeviceManager_proto_goTypes,
		DependencyIndexes: file_mqttDeviceManager_proto_depIdxs,
		MessageInfos:      file_mqttDeviceManager_proto_msgTypes,
	}.Build()
	File_mqttDeviceManager_proto = out.File
	file_mqttDeviceManager_proto_rawDesc = nil
	file_mqttDeviceManager_proto_goTypes = nil
	file_mqttDeviceManager_proto_depIdxs = nil
}
